(function(){
  let media=(()=>{try{const saved=localStorage.getItem('hanok-live-media');if(saved)return JSON.parse(saved)}catch(e){}return JSON.parse(JSON.stringify(window.HANOK_MEDIA||{gallery:[],rooms:[]}))})();
  if(!Array.isArray(media.gallery))media.gallery=[];if(!Array.isArray(media.rooms))media.rooms=[];
  const galleryList=document.getElementById('galleryMediaList'),roomList=document.getElementById('roomMediaList');
  const baseRender=render,baseRenderPreview=renderPreview;

  async function resizeImage(file,maxWidth,maxHeight,quality){
    const bitmap=await createImageBitmap(file),ratio=Math.min(1,maxWidth/bitmap.width,maxHeight/bitmap.height),width=Math.max(1,Math.round(bitmap.width*ratio)),height=Math.max(1,Math.round(bitmap.height*ratio));
    const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(bitmap,0,0,width,height);bitmap.close();
    return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('이미지 변환에 실패했습니다.')),'image/jpeg',quality));
  }
  function previewSrc(item){return item._preview||('../'+item.image)}
  function cleanBanner(b){return {id:b.id,enabled:!!b.enabled,size:b.size||'medium',icon:b.icon||'',image:b.image,title:b.title||'',message:b.message||'',buttonEnabled:!!b.buttonEnabled,buttonText:b.buttonText||'',link:b.link||'#booking'}}
  function cleanMediaItem(item){return {id:item.id,image:item.image,alt:item.alt||''}}
  function cleanMedia(){return {gallery:media.gallery.map(cleanMediaItem),rooms:media.rooms.map(cleanMediaItem)}}

  renderPreview=function(){baseRenderPreview();const visible=banners.filter(b=>b.enabled);[...previewRow.querySelectorAll('.banner img')].forEach((img,i)=>{if(visible[i]&&visible[i]._preview)img.src=visible[i]._preview})};
  render=function(){baseRender();[...editors.querySelectorAll('.card')].forEach((card,i)=>{const b=banners[i],select=card.querySelector('[data-key="image"]');if(select&&![...select.options].some(o=>o.value===b.image)){const option=new Option('직접 첨부한 이미지',b.image,true,true);select.add(option)}const label=document.createElement('label');label.className='upload-button';label.innerHTML='📷 내 배너 사진 첨부<input type="file" accept="image/*">';const input=label.querySelector('input');input.onchange=async()=>{const file=input.files&&input.files[0];if(!file)return;status.textContent='배너 사진을 웹용 크기로 준비하고 있습니다.';try{const blob=await resizeImage(file,1400,900,.88);if(b._preview)URL.revokeObjectURL(b._preview);b._upload=blob;b._preview=URL.createObjectURL(blob);b._uploadName=file.name;card.querySelector('.image-preview img').src=b._preview;renderPreview();status.textContent='새 배너 사진이 준비됐습니다. GitHub 저장 버튼을 눌러 반영하세요.'}catch(error){status.textContent='사진 처리 실패: '+error.message}};card.querySelector('.image-preview').parentElement.appendChild(label)});renderMediaLists()};

  function renderMediaList(items,container,type){container.innerHTML='';items.forEach((item,i)=>{const card=document.createElement('article');card.className='media-item';card.innerHTML='<img alt="사진 미리보기"><input type="text" placeholder="사진 설명"><div class="media-actions"><button class="move-up">↑ 위로</button><button class="move-down">↓ 아래로</button><button class="remove-media">삭제</button></div>';card.querySelector('img').src=previewSrc(item);const alt=card.querySelector('input');alt.value=item.alt||'';alt.oninput=()=>item.alt=alt.value;card.querySelector('.move-up').onclick=()=>moveMedia(type,i,-1);card.querySelector('.move-down').onclick=()=>moveMedia(type,i,1);card.querySelector('.remove-media').onclick=()=>{if(confirm('이 사진을 목록에서 삭제할까요?')){items.splice(i,1);renderMediaLists()}};container.appendChild(card)})}
  function renderMediaLists(){renderMediaList(media.gallery,galleryList,'gallery');renderMediaList(media.rooms,roomList,'rooms')}
  function moveMedia(type,index,direction){const list=media[type],next=index+direction;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];renderMediaLists()}
  async function addMediaFiles(files,type){const list=media[type],limits=type==='rooms'?[1600,1100]:[1400,1000];status.textContent='첨부한 사진을 웹용 크기로 준비하고 있습니다.';for(const file of files){try{const blob=await resizeImage(file,limits[0],limits[1],.88),preview=URL.createObjectURL(blob);list.push({id:type+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),image:'',alt:file.name.replace(/\.[^.]+$/,''),_upload:blob,_preview:preview,_uploadName:file.name})}catch(error){status.textContent=file.name+' 처리 실패: '+error.message}}renderMediaLists();status.textContent='사진이 준비됐습니다. GitHub 저장 버튼을 눌러 전체 홈페이지에 반영하세요.'}
  document.getElementById('galleryUpload').onchange=e=>{addMediaFiles([...e.target.files],'gallery');e.target.value=''};
  document.getElementById('roomUpload').onchange=e=>{addMediaFiles([...e.target.files],'rooms');e.target.value=''};

  function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
  async function blobToBase64(blob){return bytesToBase64(new Uint8Array(await blob.arrayBuffer()))}
  function githubHeaders(token){return {'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'}}
  async function createGitHubImage(path,blob,token){const api=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,response=await fetch(api,{method:'PUT',headers:{...githubHeaders(token),'Content-Type':'application/json'},body:JSON.stringify({message:'Upload website image from admin page',content:await blobToBase64(blob),branch:BRANCH})});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail.message||'사진 업로드에 실패했습니다.')}return path}
  async function updateGitHubText(path,text,token,message){const api=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,headers=githubHeaders(token),currentResponse=await fetch(api+'?ref='+encodeURIComponent(BRANCH),{headers});let sha;if(currentResponse.ok)sha=(await currentResponse.json()).sha;else if(currentResponse.status!==404)throw new Error('설정 파일을 불러오지 못했습니다. ('+currentResponse.status+')');const body={message,content:toBase64(text),branch:BRANCH};if(sha)body.sha=sha;const response=await fetch(api,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail.message||'설정 저장에 실패했습니다.')}}
  function uploadPath(type){return 'images/uploads/'+type+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.jpg'}
  async function uploadPendingImages(token){for(const b of banners){if(b._upload){b.image=await createGitHubImage(uploadPath('banner'),b._upload,token);delete b._upload;delete b._uploadName}}for(const type of ['gallery','rooms']){for(const item of media[type]){if(item._upload){item.image=await createGitHubImage(uploadPath(type==='rooms'?'room':'gallery'),item._upload,token);delete item._upload;delete item._uploadName}}}}
  function mediaConfigText(){return '/* 관리자 페이지에서 갤러리와 객실 사진 설정을 자동으로 수정합니다. */\nwindow.HANOK_MEDIA = '+JSON.stringify(cleanMedia(),null,2)+';\n'}
  applyLocal=function(){localStorage.setItem('hanok-live-banners',JSON.stringify(banners.map(cleanBanner)));localStorage.setItem('hanok-live-media',JSON.stringify(cleanMedia()));status.textContent='글과 기존 사진 배치는 현재 브라우저에 미리 반영했습니다.'};
  configText=function(){return '/* 한옥스테이 더 이천 배너 설정 */\nwindow.HANOK_BANNERS = '+JSON.stringify(banners.map(cleanBanner),null,2)+';\n'};
  saveToGitHub=async function(){const token=tokenInput.value.trim()||localStorage.getItem('hanok-github-token');if(!token){status.textContent='먼저 GitHub 토큰을 입력하세요.';tokenInput.focus();return}localStorage.setItem('hanok-github-token',token);const button=document.getElementById('githubSave');button.disabled=true;button.textContent='사진과 설정 저장 중...';try{status.textContent='새 사진을 GitHub에 업로드하고 있습니다.';await uploadPendingImages(token);status.textContent='배너 설정을 저장하고 있습니다.';await updateGitHubText('banner-config.js',configText(),token,'Update website banners from admin page');status.textContent='갤러리와 객실 사진 설정을 저장하고 있습니다.';await updateGitHubText('site-media-config.js',mediaConfigText(),token,'Update website gallery and room images');applyLocal();status.textContent='저장 완료! GitHub Pages 배포 후 모든 방문자에게 새 사진이 반영됩니다.';render()}catch(error){status.textContent='저장 실패: '+error.message}finally{button.disabled=false;button.textContent='GitHub에 저장하고 반영'}};
  document.getElementById('localSave').onclick=applyLocal;document.getElementById('githubSave').onclick=saveToGitHub;
})();
